# import libraries

In [93]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline
import datetime
from sklearn.metrics import mean_squared_error,mean_absolute_error,root_mean_squared_error,r2_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# load data

In [94]:
data=pd.read_csv("carprice_ml_pro.csv")
df=pd.DataFrame(data)
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Cargo Volumn,Alloy Wheel Size_2,City,Gear Box_1,Rear Brake Type_1,Front Brake Type_1,Acceleration_1,Top Speed_1,Drive Type_1,Turning Radius_1
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,235-litres,NaN,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,352-litres,16,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,242-litres,14,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,407-litres,14,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,353-litres,16,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,313,NaN,Kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8365,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,177-litres,NaN,Kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8366,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,475-litres,NaN,Kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8367,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,236-liters,NaN,Kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8368,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,410-litres,NaN,Kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# create new features

In [95]:
current_year=datetime.datetime.now().year
current_year

2025

In [96]:
df["Car Age"]=current_year-df["modelYear"]
df["Car Age"]

0       10
1        7
2        7
3       11
4       10
        ..
8364     3
8365    11
8366    14
8367    13
8368     8
Name: Car Age, Length: 8369, dtype: int64

In [97]:
df["Length"]=df["Length"].str.replace("mm","").str.replace(",","").str.strip().astype(float)
df["Width"]=df["Width"].str.replace("mm","").str.replace(",","").str.strip().astype(float)
df["Height"]=df["Height"].str.replace("mm","").str.replace(",","").str.replace("-","").str.strip().astype(float)

In [98]:
df["Car Size"]=df["Length"]*df["Width"]*df["Height"]
df["Car Size"].unique()

array([9.50584912e+09, 1.16220061e+10, 9.47043117e+09, 1.00801840e+10,
       1.22424225e+10, 1.31037804e+10, 9.22082775e+09, 1.13491958e+10,
       1.15350345e+10, 1.05266252e+10, 9.49984800e+09, 1.03444449e+10,
       1.54681852e+10, 1.44357199e+10, 1.02813322e+10, 1.16135047e+10,
       1.12510710e+10, 1.31187614e+10, 1.02067448e+10, 1.34649444e+10,
       1.66939261e+10, 9.26398200e+09, 8.64423375e+09, 1.40692669e+10,
       1.36849871e+10, 1.31335956e+10, 9.14685850e+09, 1.28867992e+10,
       1.36495682e+10, 1.53841102e+10, 1.59817800e+10, 1.03995350e+10,
       1.18199025e+10, 1.34506631e+10, 7.69828312e+09, 1.58973872e+10,
       9.40161530e+09, 1.27767150e+10, 1.56674131e+10, 7.52648250e+09,
       2.02795520e+10, 1.57666901e+10, 1.92437940e+10, 8.68370103e+09,
       1.16236463e+10, 9.61062975e+09, 9.50917488e+09, 1.09243593e+10,
       1.23889780e+10, 1.48568921e+10, 1.01934720e+10, 1.32979542e+10,
       1.33655686e+10, 1.25037569e+10, 1.02740400e+10, 1.06721431e+10,
       1.11758130e+10, 9.70246562e+09, 1.09916091e+10, 1.04308444e+10,
       1.68701199e+10, 8.95637700e+09, 8.86301625e+09, 8.58591040e+09,
       1.44238790e+10, 1.18362542e+10, 1.52437120e+10, 9.09720000e+09,
       7.79567000e+09, 1.12097212e+10, 8.12587500e+09, 1.09417809e+10,
       1.14445988e+10, 1.50337880e+10, 1.34921250e+10, 1.26549990e+10,
       1.25845950e+10, 1.21146892e+10, 1.16988472e+10, 1.30277374e+10,
       1.33259714e+10, 1.60038186e+10, 7.99474400e+09, 1.01397870e+10,
       1.67150834e+10, 1.00448242e+10, 9.97353500e+09, 1.14029934e+10,
       1.66844978e+10, 1.16704456e+10, 1.37427250e+10, 1.63218204e+10,
       1.13232210e+10, 1.44229378e+10, 1.44742020e+10, 9.81177712e+09,
       1.39885200e+10, 1.31030852e+10, 1.42024960e+10, 1.55010240e+10,
       1.48925801e+10, 1.27616236e+10, 1.17277220e+10, 1.05009574e+10,
       1.21811599e+10, 1.20554654e+10, 1.09193779e+10, 1.17306456e+10,
       1.09335160e+10, 1.31102302e+10, 1.11017599e+10, 1.66234800e+10,
       1.32761751e+10, 1.21025520e+10, 9.98439750e+09, 1.42428440e+10,
       9.32860404e+09, 1.90501580e+10, 1.10486880e+10, 1.35952236e+10,
       9.01446250e+09, 9.13669250e+09, 1.13373003e+10, 1.19868320e+10,
       1.19754835e+10, 1.29035066e+10, 9.72357500e+09, 8.77796101e+09,
       7.92174562e+09, 9.92494750e+09, 1.05297214e+10, 1.36417956e+10,
       1.09703125e+10, 1.78189976e+10, 1.20104840e+10, 1.34373206e+10,
       1.07565120e+10, 1.47743387e+10,            nan, 1.42270830e+10,
       8.79468143e+09, 1.72327592e+10, 1.60158200e+10, 1.14340496e+10,
       1.48687434e+10, 1.04438250e+10, 1.17420241e+10, 8.81357125e+09,
       1.15963614e+10, 1.14606492e+10, 8.49125960e+09, 1.19974675e+10,
       8.24317884e+09, 1.03814070e+10, 9.91784250e+09, 1.24841213e+10,
       1.09577750e+10, 1.65203333e+10, 1.07829139e+10, 1.49211397e+10,
       1.42458702e+10, 9.09798120e+09, 1.49176640e+10, 9.22272000e+09,
       1.02895756e+10, 1.51758904e+10, 1.24224517e+10, 9.25228000e+09,
       1.18400098e+10, 1.69886662e+10, 1.09477761e+10, 1.29193602e+10,
       1.10377225e+10, 1.26226923e+10, 9.69184418e+09, 1.75806782e+10,
       1.81718531e+10, 1.85301923e+10, 1.44731513e+10, 1.36311707e+10,
       1.17817943e+10, 1.39381515e+10, 8.96198625e+09, 7.34042680e+09,
       1.21829400e+10, 7.79278800e+09, 1.20362190e+10, 1.38062649e+10,
       1.06647314e+10, 1.16858180e+10, 9.12361725e+09, 1.55537648e+10,
       9.96515197e+09, 9.72223200e+09, 1.30304714e+10, 1.21401070e+10,
       1.29696840e+10, 1.01278117e+10, 1.33860864e+10, 8.82481600e+09,
       1.20957375e+10, 9.89264062e+09, 1.61518050e+10, 1.55730802e+10,
       9.71644800e+09, 1.08598650e+10, 7.42517912e+09, 1.38598300e+10,
       1.71868500e+10, 1.04333731e+10, 9.26130816e+09, 1.37124846e+10,
       1.11243698e+10, 1.61792904e+10, 1.58459900e+10, 1.51004485e+10,
       1.07002879e+10, 1.17408256e+10, 1.34708062e+10, 7.46136125e+09,
       1.28009478e+10, 1.21016250e+10, 1.40886690e+10, 7.93158795e+09,
       1.22696982e+10, 1.01107440e+10, 1.31506620e+10, 2.06179735e+10,
       1.13359225e+10, 1.09419298e+10, 7.50546810e+09, 1.01640590e+10,
       1.03265756e+10, 1.31059970e+10, 1.16487754e+10, 1.27066843e+10,
       1.62385020e+10, 9.68285745e+09, 1.03676430e+10, 1.05981555e+10,
       1.63243777e+10, 1.30142734e+10, 1.50524532e+10, 1.00554732e+10,
       1.13181562e+10, 1.42351140e+10, 7.66476375e+09, 1.48938989e+10,
       1.39577760e+10, 1.28519245e+10, 1.61972481e+10, 1.26567000e+10,
       7.65372426e+09, 1.44719627e+10, 1.14001362e+10, 1.19894388e+10,
       1.10880120e+10, 1.00883160e+10, 1.51776521e+10, 1.03534200e+10,
       1.60310542e+10, 9.91750923e+09, 1.52665972e+10, 9.94926240e+09,
       1.12880644e+10, 1.17712292e+10, 1.54370563e+10, 8.35874274e+09,
       1.02586719e+10, 1.78998421e+10, 1.20747325e+10, 8.92762560e+09,
       1.11822370e+10, 1.17584233e+10, 1.45712808e+10, 1.71684975e+10,
       1.50537396e+10, 1.30582256e+10, 1.21904975e+10, 9.99649600e+09,
       1.42361305e+10, 1.81118531e+10, 1.24743048e+10, 1.28039797e+10,
       1.22092104e+10, 1.23670042e+10, 1.48910898e+10, 1.88023443e+10,
       1.79252724e+10, 8.47500320e+09, 1.59296100e+10, 7.57124875e+09,
       1.95289781e+10, 9.62936100e+09, 1.02624006e+10, 1.21956353e+10,
       1.24581818e+10, 1.34734242e+10, 1.22305355e+10, 9.75712500e+09,
       8.34400000e+09, 1.23457972e+10, 8.22685750e+09, 8.98560000e+09,
       8.99722688e+09, 1.03047919e+10, 1.07927574e+10, 1.94445418e+10,
       1.65562441e+10, 9.33913218e+09, 1.33333117e+10, 1.01437444e+10,
       1.34127875e+10, 1.30584960e+10, 1.73991052e+10, 1.43476475e+10,
       1.15329375e+10, 1.68970494e+10, 1.49722963e+10, 1.88205325e+10,
       2.04750227e+10, 1.60987950e+10, 1.34724851e+10, 1.09160542e+10,
       1.14414010e+10, 1.65548624e+10, 6.74737200e+09, 1.02016320e+10,
       1.26870150e+10, 1.18334734e+10, 1.20510900e+10, 1.44592886e+10,
       1.69989561e+10, 1.01447609e+14, 9.74399625e+09, 1.07666139e+10,
       1.34202306e+10, 1.28801126e+10, 1.65961093e+10, 1.48154277e+10,
       1.00667385e+10, 1.26579648e+10, 1.88131680e+10, 9.79984130e+09,
       9.73241925e+09, 1.30998500e+10, 9.84948074e+09, 1.13323039e+10,
       1.33744205e+10, 1.09628442e+10, 1.49013278e+10, 1.06242725e+10,
       1.19045924e+10, 1.10920005e+10, 1.71321257e+10, 1.02410826e+10,
       1.28888629e+10, 8.58429000e+09, 1.50953010e+10, 1.13513527e+10,
       1.03262906e+10, 1.08851205e+10, 9.97041375e+09, 1.65130800e+10,
       1.18327657e+10, 1.02447056e+10, 1.12168125e+10, 1.49010680e+10,
       1.52527956e+10, 1.56794220e+10, 1.36648814e+10, 1.28870190e+10,
       1.48183230e+10, 1.30323250e+10, 1.01471175e+10, 1.53138992e+10,
       1.68649646e+10, 9.71215312e+09, 1.42296234e+10, 1.28140360e+10,
       1.20422441e+10, 2.04414226e+10, 1.30781220e+10, 1.34072519e+10,
       1.47406761e+10, 1.20650965e+10, 1.33175593e+10, 8.46945000e+09,
       1.31622060e+10, 1.46300880e+10, 1.37935887e+10, 9.74198400e+09,
       9.88236374e+09, 1.47347978e+10, 1.20495192e+10, 1.18789135e+10,
       1.70875468e+10, 1.19234586e+10, 1.05084179e+10, 1.64655312e+10,
       2.07772046e+10, 9.94090380e+09, 1.46999740e+10, 1.44614342e+10,
       1.61075000e+10, 1.29306692e+10, 1.69892642e+10, 1.35282042e+10,
       1.12751590e+10, 1.10314314e+10, 2.09065037e+10, 1.53192963e+10,
       1.56141368e+10, 1.45147080e+10, 1.51363359e+10, 1.60506057e+10,
       1.90762703e+10, 1.42329470e+10, 1.74278219e+10, 1.32778067e+10,
       2.03191605e+10, 1.60945253e+10, 8.61872000e+09, 1.79207669e+10,
       9.40826425e+09, 1.26038283e+10, 1.57953530e+10, 1.48019802e+10,
       1.68929020e+10, 1.80735750e+10, 1.18063056e+10, 1.69950817e+10,
       1.18257920e+10, 1.80424035e+10, 1.46389904e+10, 7.79102375e+09,
       1.37830962e+10, 1.33323737e+10, 1.08290480e+10, 1.22305537e+10,
       1.81216080e+10, 1.29247650e+10, 1.51126320e+10, 1.38057750e+10,
       1.38796712e+10, 1.19285041e+10, 1.13165175e+10, 1.63934616e+10,
       1.20030144e+10, 1.44428400e+10, 1.46683080e+10, 1.43553159e+10,
       1.38467306e+10, 1.09293212e+10, 9.44802262e+09, 1.61501915e+10,
       9.87189012e+09, 1.36639649e+10, 1.28298074e+10, 1.75385700e+10,
       1.68337298e+10, 1.49643843e+10, 8.99899000e+09, 7.53828250e+09,
       1.32655324e+10, 1.32907637e+10, 1.20026031e+10, 1.27154577e+10,
       1.15788750e+10, 1.62538175e+10, 1.43511102e+10, 9.59789250e+09,
       1.46505820e+10, 1.31859980e+10, 1.14401059e+10, 1.49881624e+10,
       1.85356886e+10, 1.10540966e+10, 2.15641920e+10, 1.04936708e+10,
       1.34463513e+10, 1.44020953e+10, 1.13240333e+10, 1.28087305e+10,
       1.61234180e+10, 1.26623232e+10, 1.61306446e+10, 1.27589826e+10,
       1.01270318e+10, 1.28956862e+10, 1.13802612e+10, 1.30137360e+10,
       1.62093908e+10, 1.30297524e+10, 9.64846688e+09, 1.80113100e+10,
       1.06418812e+10, 1.51638616e+10, 1.65341575e+10, 1.45229968e+10,
       1.34767800e+10, 1.15082385e+10, 1.29848810e+10, 1.55535810e+10,
       1.49312946e+10, 1.60362375e+10, 1.49649113e+10, 1.09197396e+10,
       1.31781702e+10, 1.57769378e+10, 9.68700200e+09, 1.18126800e+10,
       9.66192375e+09, 1.21526340e+10, 1.56521456e+10, 1.28714410e+10,
       1.22494051e+10, 1.10915545e+10, 1.48816882e+10, 1.08799444e+10,
       1.26895841e+10, 1.47836830e+10, 9.66137062e+09, 8.39372120e+09,
       9.97887092e+09, 8.85538375e+09, 1.43867269e+10, 1.14507230e+10,
       1.46143182e+10, 1.46685055e+10, 1.61078052e+10, 1.36086453e+10,
       1.19050791e+10, 1.31786030e+10, 1.15010400e+10, 1.13533259e+10,
       1.26975459e+10, 1.22200808e+10, 1.37318624e+10, 1.19390839e+10,
       1.57205600e+10, 8.70726602e+09, 1.33431740e+10])

In [99]:
selected_feature=['Car Age','Car Size','ft', 'bt', 'km', 'transmission', 'ownerNo','oem',
                  'model', 'modelYear', 'price','Insurance Validity','Mileage', 'Engine',
                  ' Seats','Color','City']

# drop unwanted columns

In [100]:
new_df=df.drop(columns=['it', 'owner',  'centralVariantId', 'variantName',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'Registration Year',
       'Fuel Type', 'Kms Driven', 'RTO',
       'Ownership', 'Engine Displacement', 'Transmission',
       'Year of Manufacture', 'Max Power', 'Torque',
       'Seats_1', 'Wheel Size', 'Engine Type', 'Displacement',
       'Max Power_1', 'Max Torque', 'No of Cylinder', 'Values per Cylinder',
       'Value Configuration', 'Fuel Suppy System', 'BoreX Stroke',
       'Compression Ratio', 'Turbo Charger', 'Super Charger',
       'Seating Capacity', 'Steering Type', 'Tyre Type', 'Alloy Wheel Size',
       'No Door Numbers', 'Length', 'Width', 'Height', 'Wheel Base',
       'Front Tread', 'Rear Tread', 'Kerb Weight', 'Gross Weight',
       'Ground Clearance Unladen', 'Seating Capacity_1', 'Steering Type_1',
       'Tyre Type_1', 'Alloy Wheel Size_1', 'No Door Numbers_1', 'Gear Box',
       'Drive Type', 'Seating Capacity_2', 'Steering Type_2', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Top Speed', 'Acceleration',
       'Tyre Type_2', 'No Door Numbers_2', 'Cargo Volumn',
       'Alloy Wheel Size_2', 'Gear Box_1', 'Rear Brake Type_1',
       'Front Brake Type_1', 'Acceleration_1', 'Top Speed_1', 'Drive Type_1',
       'Turning Radius_1'],inplace=True)
new_df

# handle numerical columns

In [101]:
df["km"]=df["km"].str.replace(",","").str.strip().astype(float)
df["Insurance Validity"]=df["Insurance Validity"].str.replace("2","Second Party").str.replace("1","First Party").str.strip()
df["Seats"]=df["Seats"].str.replace("Seats","").str.strip().astype(float)
df["Mileage"]=df["Mileage"].str.replace("kmpl","").str.replace("km/kg",'').str.strip().astype(float)
df["Engine"]=df["Engine"].str.replace("CC","").str.strip().astype(float)
df["price"]=df["price"].str.replace("Lakh","").str.replace("Crore","").str.replace(",","").str.replace("₹","").str.strip().astype(float)

# drop duplicate values

In [102]:
df.drop_duplicates(inplace=True)

In [103]:
df.dropna(subset=["Mileage"],inplace=True)
df.shape

(7975, 17)

In [104]:
df.dropna(subset=["Car Size"],inplace=True)
df.shape

(7915, 17)

# handle missing values

In [105]:
df["bt"].fillna(df["bt"].mode()[0],inplace=True)
df["Insurance Validity"].fillna(df["Insurance Validity"].mode()[0],inplace=True)
df["Seats"].fillna(df["Seats"].median(),inplace=True)
df["Engine"].fillna(df["Engine"].mode()[0],inplace=True)
df["Color"].fillna(df["Color"].mode()[0],inplace=True)

# handle outliers

In [106]:
q1=df["price"].quantile(0.25)
q3=df["price"].quantile(0.75)
iqr=q3-q1
lf=q1-1.5*iqr
uf=q3+1.5*iqr
dff=df[(df["price"]>lf)&(df['price']<uf)]
dff

,ft,bt,km,transmission,ownerNo,oem,model,modelYear,price,Insurance Validity,Seats,Mileage,Engine,Color,City,Car Age,Car Size
0,Petrol,Hatchback,120000.0,Manual,3,Maruti,Maruti Celerio,2015,4.00,Third Party insurance,5.0,23.10,998.0,White,Bangalore,10,9.505849e+09
1,Petrol,SUV,32706.0,Manual,2,Ford,Ford Ecosport,2018,8.11,Comprehensive,5.0,17.00,1497.0,White,Bangalore,7,1.162201e+10
2,Petrol,Hatchback,11949.0,Manual,1,Tata,Tata Tiago,2018,5.85,Comprehensive,5.0,23.84,1199.0,Red,Bangalore,7,9.470431e+09
3,Petrol,Sedan,17794.0,Manual,1,Hyundai,Hyundai Xcent,2014,4.62,Comprehensive,5.0,19.10,1197.0,Others,Bangalore,11,1.008018e+10
4,Diesel,SUV,60000.0,Manual,1,Maruti,Maruti SX4 S Cross,2015,7.90,Third Party insurance,5.0,23.65,1248.0,Gray,Bangalore,10,1.224242e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,Petrol,Hatchback,10000.0,Manual,1,Maruti,Maruti Celerio,2022,5.10,Third Party insurance,5.0,25.24,998.0,Others,Kolkata,3,9.509175e+09
8365,Petrol,Hatchback,120000.0,Manual,1,Maruti,Maruti Alto 800,2014,1.80,Third Party insurance,5.0,22.74,796.0,Others,Kolkata,11,7.461361e+09
8366,Petrol,Sedan,50000.0,Automatic,3,Mercedes-Benz,Mercedes-Benz C-Class,2011,5.50,Third Party insurance,5.0,11.74,1796.0,Others,Kolkata,14,1.175842e+10
8367,Petrol,Hatchback,40000.0,Manual,1,Maruti,Maruti Ritz,2012,1.40,Third Party insurance,5.0,18.50,1197.0,Others,Kolkata,13,1.027404e+10
8368,Diesel,SUV,120000.0,Manual,2,Renault,Renault Duster,2017,5.00,Third Party insurance,5.0,19.72,1461.0,Others,Kolkata,8,1.332597e+10

# remane columns

In [107]:
dff=dff.rename(columns={"ft":"Fuel Type","bt":"Body Type","transmission":"Transmission","ownerNo":"Owner No","model":"Model",
                        "modelYear":"Model Year","price":"Price","km":"Kilometer","oem":"Brand"})
dff

,Fuel Type,Body Type,Kilometer,Transmission,Owner No,Brand,Model,Model Year,Price,Insurance Validity,Seats,Mileage,Engine,Color,City,Car Age,Car Size
0,Petrol,Hatchback,120000.0,Manual,3,Maruti,Maruti Celerio,2015,4.00,Third Party insurance,5.0,23.10,998.0,White,Bangalore,10,9.505849e+09
1,Petrol,SUV,32706.0,Manual,2,Ford,Ford Ecosport,2018,8.11,Comprehensive,5.0,17.00,1497.0,White,Bangalore,7,1.162201e+10
2,Petrol,Hatchback,11949.0,Manual,1,Tata,Tata Tiago,2018,5.85,Comprehensive,5.0,23.84,1199.0,Red,Bangalore,7,9.470431e+09
3,Petrol,Sedan,17794.0,Manual,1,Hyundai,Hyundai Xcent,2014,4.62,Comprehensive,5.0,19.10,1197.0,Others,Bangalore,11,1.008018e+10
4,Diesel,SUV,60000.0,Manual,1,Maruti,Maruti SX4 S Cross,2015,7.90,Third Party insurance,5.0,23.65,1248.0,Gray,Bangalore,10,1.224242e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,Petrol,Hatchback,10000.0,Manual,1,Maruti,Maruti Celerio,2022,5.10,Third Party insurance,5.0,25.24,998.0,Others,Kolkata,3,9.509175e+09
8365,Petrol,Hatchback,120000.0,Manual,1,Maruti,Maruti Alto 800,2014,1.80,Third Party insurance,5.0,22.74,796.0,Others,Kolkata,11,7.461361e+09
8366,Petrol,Sedan,50000.0,Automatic,3,Mercedes-Benz,Mercedes-Benz C-Class,2011,5.50,Third Party insurance,5.0,11.74,1796.0,Others,Kolkata,14,1.175842e+10
8367,Petrol,Hatchback,40000.0,Manual,1,Maruti,Maruti Ritz,2012,1.40,Third Party insurance,5.0,18.50,1197.0,Others,Kolkata,13,1.027404e+10
8368,Diesel,SUV,120000.0,Manual,2,Renault,Renault Duster,2017,5.00,Third Party insurance,5.0,19.72,1461.0,Others,Kolkata,8,1.332597e+10

# split target and features

In [108]:
x=dff.drop("Price",axis=1)
y=dff["Price"]

# split train and test data

In [109]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# create pipeline

In [110]:
numerical_features=x.select_dtypes(include=np.number).columns.tolist()
categorical_features=x.select_dtypes(exclude=np.number).columns.tolist()

In [111]:
numerical_transformer=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
])

In [112]:
categorical_transformer=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('ordinal',OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1))
])

In [113]:
preprocessor=ColumnTransformer(
    transformers=[
        ('num',numerical_transformer,numerical_features),
        ('cat',categorical_transformer,categorical_features)
    ],
    remainder='passthrough'
)

In [114]:
model_pipeline=Pipeline(steps=[
    ('preprocessor',preprocessor),
    ('regressor',RandomForestRegressor(n_estimators=100,random_state=42))
])

# fit pipeline

In [115]:
print("training the model.....")
model_pipeline.fit(x_train,y_train)
print("model training complete.")

training the model.....
model training complete.

# model prediction

In [116]:
print("making prediction...")
y_pred=model_pipeline.predict(x_test)
print("prediction completed..")

making prediction...
prediction completed..

# evaluate the model

In [117]:
r2_score=r2_score(y_test,y_pred)
print("r2_score :",r2_score)

r2_score : 0.8858771458250427

In [118]:
x_train_processed=preprocessor.fit_transform(x_train)
print("\n sample of preprocessed training data :",x_train_processed[:5])

 sample of preprocessed training data : [[ 6.51418620e-02 -5.75533924e-01  7.28723635e-01 -2.78319064e-01
   4.73012551e-01 -9.00283176e-01 -7.28723635e-01 -3.02287693e-02
   4.00000000e+00  2.00000000e+00  0.00000000e+00  1.90000000e+01
   1.19000000e+02  4.00000000e+00  4.10000000e+01  3.00000000e+00]
 [ 8.41388469e-01 -5.75533924e-01  1.75058711e-01 -2.78319064e-01
  -2.20004694e-01 -8.97626806e-01 -1.75058711e-01 -2.93845167e-02
   4.00000000e+00  6.00000000e+00  1.00000000e+00  6.00000000e+00
   3.90000000e+01  0.00000000e+00  4.10000000e+01  2.00000000e+00]
 [ 6.53674562e-01 -5.75533924e-01  1.00555610e+00  3.03097681e+00
  -1.04081809e-01  3.32272477e-01 -1.00555610e+00 -2.91092377e-02
   4.00000000e+00  3.00000000e+00  1.00000000e+00  1.90000000e+01
   1.22000000e+02  0.00000000e+00  8.40000000e+01  4.00000000e+00]
 [ 1.51347890e-01  9.98318185e-01 -3.78606213e-01 -2.78319064e-01
   1.90765528e-01 -9.00283176e-01  3.78606213e-01 -3.03476416e-02
   4.00000000e+00  2.00000000e+00  1.00000000e+00  1.90000000e+01
   1.37000000e+02  0.00000000e+00  8.40000000e+01  1.00000000e+00]
 [ 3.20060597e-01  9.98318185e-01  1.75058711e-01 -2.78319064e-01
   1.44827682e+00  4.27901795e-01 -1.75058711e-01 -2.97003165e-02
   1.00000000e+00  6.00000000e+00  1.00000000e+00  8.00000000e+00
   5.50000000e+01  0.00000000e+00  9.00000000e+00  1.00000000e+00]]

# save as pickle file

In [119]:
import pickle

In [120]:
filename='car_price_prediction.pkl'

In [121]:
with open(filename,'wb') as file:
    pickle.dump(model_pipeline,file)
print(f"model saved as {filename}")

model saved as car_price_prediction.pkl

# load model from the pickle file

In [122]:
with open('car_price_prediction.pkl','rb') as file:
    loaded_model=pickle.load(file)